# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20161128_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.CharField(max_length=1, verbose_name='Начальная буква диапазона')),
                ('end', models.CharField(max_length=1, verbose_name='Конечная буква диапазона')),
            ],
        ),
    ]
