# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_lettergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['lastname'], 'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterModelTable(
            name='lettergroup',
            table='letter_group',
        ),
    ]
