# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'db_table': 'departments_list',
                'verbose_name': 'Список отделов',
                'verbose_name_plural': 'Списки отделов',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('begin_work', models.DateTimeField(verbose_name='Начало работы')),
                ('end_work', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Окончание работы')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeesList.DepartmentsList')),
            ],
            options={
                'db_table': 'employee',
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='PositionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'db_table': 'positions_list',
                'verbose_name': 'Список сотрудников',
                'verbose_name_plural': 'Списки сотрудников',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeesList.PositionsList'),
        ),
    ]
