# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeesList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='begin_work',
            field=models.DateTimeField(verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_work',
            field=models.DateTimeField(blank=True, verbose_name='Окончание работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='secondname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
